# Lineare Regression mit mehreren Variablen

In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.array([6, 8, 9, 11])
reg = LinearRegression().fit(X, y)


In [7]:
reg.coef_

array([1., 2.])

In [8]:
reg.intercept_

3.0000000000000018

In [9]:
reg.predict(np.array([[3, 5]]))

array([16.])

In [10]:
import pandas as pd

df = pd.read_csv("data/hotels.csv")

df.head()

Gewinn  Preis in Mio  Quadratmeter    Stadt
0  119000.0         21.88        3938.0   Berlin
1  250000.0         27.95        3986.0  München
2  250000.0         16.09        2574.0     Köln
3  145000.0         27.58        4155.0  München
4  110000.0         23.76        3795.0   Berlin

In [11]:
#df[["Gewinn", "Quadratmeter"]]
#df[df["Gewinn"] > 250000]

In [12]:
df[["Preis in Mio", "Gewinn"]]

Preis in Mio    Gewinn
0           21.88  119000.0
1           27.95  250000.0
2           16.09  250000.0
3           27.58  145000.0
4           23.76  110000.0
..            ...       ...
145         10.50   45000.0
146         23.80  250000.0
147         12.86   32000.0
148         15.80   35000.0
149         17.09   90000.0

[150 rows x 2 columns]

In [13]:
X = df[["Gewinn", "Quadratmeter"]].values
Y = df[["Preis in Mio"]].values

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 0, test_size = 0.25)

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [16]:
print(model.intercept_)

[6.48370247]


In [17]:
print(model.coef_)

[[6.39855984e-06 3.89642288e-03]]


In [18]:
# 6.48370247 + [Gewinn] * 6.39855984e-06 + [Quadratmeter] * 3.89642288e-03

In [19]:
X_test

array([[5.600e+04, 2.218e+03],
       [7.100e+04, 3.162e+03],
       [1.380e+05, 1.461e+03],
       [1.200e+05, 4.681e+03],
       [2.000e+03, 8.200e+01],
       [1.630e+05, 3.619e+03],
       [3.400e+04, 1.847e+03],
       [2.600e+04, 1.241e+03],
       [2.500e+05, 1.355e+03],
       [2.500e+05, 5.702e+03],
       [2.270e+05, 1.696e+03],
       [8.300e+04, 4.561e+03],
       [1.250e+05, 3.910e+03],
       [9.900e+04, 2.630e+03],
       [6.400e+04, 1.993e+03],
       [2.300e+04, 7.030e+02],
       [9.700e+04, 3.674e+03],
       [3.000e+03, 1.140e+02],
       [2.100e+04, 1.215e+03],
       [1.020e+05, 2.700e+03],
       [1.250e+05, 5.643e+03],
       [4.000e+03, 1.710e+02],
       [8.400e+04, 3.815e+03],
       [1.140e+05, 3.706e+03],
       [1.350e+05, 3.224e+03],
       [1.340e+05, 2.412e+03],
       [1.560e+05, 5.099e+03],
       [1.420e+05, 5.427e+03],
       [6.200e+04, 1.799e+03],
       [3.200e+04, 1.492e+03],
       [3.500e+04, 1.021e+03],
       [1.900e+04, 7.230e+02],
       [

In [20]:
y_test_pred = model.predict(X_test)
y_test_pred

array([[15.48428777],
       [19.25848937],
       [13.05937756],
       [25.49068515],
       [ 6.81600627],
       [21.62782213],
       [13.89794657],
       [11.48552582],
       [13.36299543],
       [30.30074569],
       [14.54450876],
       [24.78636769],
       [22.51853591],
       [17.36475207],
       [14.6587811 ],
       [ 9.37005463],
       [21.41982044],
       [ 6.94709036],
       [11.35222603],
       [17.65669735],
       [29.27103676],
       [ 7.17558502],
       [21.88603479],
       [21.65328149],
       [19.90957541],
       [16.73928148],
       [27.34973807],
       [28.53818494],
       [13.89007794],
       [12.50191932],
       [10.68589983],
       [ 9.42238885],
       [10.12896444],
       [ 9.83562033],
       [15.90798701],
       [13.00094789],
       [17.32972215],
       [18.35066072]])

In [21]:
y_test

array([[14.56],
       [16.32],
       [13.09],
       [22.87],
       [ 8.94],
       [19.13],
       [13.77],
       [ 9.63],
       [10.41],
       [32.78],
       [12.98],
       [23.6 ],
       [20.27],
       [21.26],
       [13.86],
       [ 9.76],
       [24.81],
       [ 6.62],
       [ 8.69],
       [14.16],
       [28.49],
       [ 6.95],
       [22.4 ],
       [24.87],
       [16.94],
       [15.54],
       [24.78],
       [30.14],
       [16.15],
       [17.75],
       [ 7.91],
       [ 7.98],
       [ 6.73],
       [ 6.3 ],
       [13.21],
       [10.94],
       [19.59],
       [15.18]])

In [22]:
print("Vorhersage - Wahrer Wert (Testdaten)")
for i in range(0, len(y_test_pred)):
    print(str(y_test_pred[i][0]) + " - " + str(y_test[i][0]))

Vorhersage - Wahrer Wert (Testdaten)
15.484287770456307 - 14.56
19.25848936697959 - 16.32
13.059377556544964 - 13.09
25.490685154062852 - 22.87
6.8160062670562525 - 8.94
21.627822128095936 - 19.13
13.89794656549663 - 13.77
11.48552582135802 - 9.63
13.362995432755909 - 10.41
30.300745693396017 - 32.78
14.544508758730883 - 12.98
24.786367694531798 - 23.6
22.5185359125309 - 20.27
17.364752070043462 - 21.26
14.658781101070202 - 13.86
9.370054632254531 - 9.76
21.419820437400865 - 24.81
6.947090359060695 - 6.62
11.352226027295266 - 8.69
17.656697351169136 - 14.16
29.271036764081238 - 28.49
7.1755850230725 - 6.95
21.886034785667135 - 22.4
21.653281486765614 - 24.87
19.90957541499908 - 16.94
16.739281476364937 - 15.54
27.349738072086637 - 24.78
28.538184939132954 - 30.14
13.890077942623035 - 16.15
12.501919323322051 - 17.75
10.685899826208408 - 7.91
9.422388850520344 - 7.98
10.128964442111489 - 6.73
9.835620333614967 - 6.3
15.90798700549315 - 13.21
13.00094788689616 - 10.94
17.329722152677313 