# Nützliches für Machine Leaning in Python II





## Numpy Where

In [18]:
import numpy as np

In [19]:
# Erstes Argument: beliebige n langes Array von True / False
# Zweites und Drittes Argument: Arrays mit Länge 1 bis max. n.
np.where([True, True], [1,2], [3,4])

array([1, 2])

In [20]:
np.where([True, False], [1,2], [3,4])

array([1, 4])

In [21]:
np.where([True, False, True, False], [10,20,30, 40],[1,2,3,4])

array([10,  2, 30,  4])

In [22]:
# Das geht auch nur mit einem Eintrag beim 2. u. dritten Argument. 
np.where([True, False, True], [0], [1000, 2000, 3000])

array([   0, 2000,    0])

In [23]:
#sieht ziemlich binär aus:
np.where(np.array([1,2,3,4,5,6]) < 4, [1], [0])

array([1, 1, 1, 0, 0, 0])

In [24]:
np.where([True, False, True], [False], [True])

array([False,  True, False])

In [25]:
np.where([True, False, False, False, False, False, True], [False], [True])

array([False,  True,  True,  True,  True,  True, False])

In [26]:
#Auf Numpy-Array kann man ja Operatoren anwenden (s. oben)...
np.array([1,2,3,4,5,6]) < 4

array([ True,  True,  True, False, False, False])

In [27]:
np.array([True, False, False, False, False, False, True]) == False

array([False,  True,  True,  True,  True,  True, False])

In [28]:
#das kann man dann mit where kombinieren:
np.where(np.array([1,2,3,4,5,6]) >= 4, ["bestanden"], ["nicht bestanden"])

array(['nicht bestanden', 'nicht bestanden', 'nicht bestanden',
       'bestanden', 'bestanden', 'bestanden'], dtype='<U15')

In [29]:
#oder auch anders herum:
np.where(np.array(["sehr-gut","gut","befriedigend","ausreichend","nicht-bestanden"]) == "nicht-bestanden", [0], [1])

array([1, 1, 1, 1, 0])

In [30]:
# Numpy-Where kann man also auch für die Wandlung von nominalen Attributen 
# in numerische Attribute gut gebrauchen. Auch möglich ist das 
# Zusammenfassen einzelner Ausprägungen. Beispiel: Farbe D ist bei Diamanten 
# sehr selten. Für die Preisprognose also wichtig: D oder nicht-D ?
import pandas as pd

df = pd.read_csv("data/diamonds.csv")
#df.head(200)
df[df['color'] == "D" ] 

carat        cut color clarity  depth  table  price     x     y     z
28      0.23  Very Good     D     VS2   60.5   61.0    357  3.96  3.97  2.40
34      0.23  Very Good     D     VS1   61.9   58.0    402  3.92  3.96  2.44
38      0.26  Very Good     D     VS2   60.8   59.0    403  4.13  4.16  2.52
42      0.26       Good     D     VS2   65.2   56.0    403  3.99  4.02  2.61
43      0.26       Good     D     VS1   58.4   63.0    403  4.19  4.24  2.46
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[6775 rows x 10 columns]

In [31]:
sum(np.where(df["color"] == "D",[1], [0]))

6775

In [32]:
df["color_d"] = np.where(df["color"] == "D",[1], [0])
df

carat        cut color clarity  depth  table  price     x     y     z  \
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64   

       color_d  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
53935        1  
53936        1  
53937        1  
53938        0  
53939        1  

[53940 rows x 11 columns]

In [33]:
df["color"]

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: object

In [34]:
sum(df["color_d"])

6775